# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.
{
    'name': 'as_hospital',
    'version': '1.2',
    'summary': "hospital module",
    'sequence': 10,
    'author': "anand",
    'description': """
My Hospital module
""",
    'category': 'Hospital/Hospital',
    'website': 'https://www.odoo.com/app/invoicing',
    'depends': ['mail', 'website'],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'wizard/create_case.xml',
        'wizard/cancel_case.xml',
        'wizard/search_case.xml',
        'wizard/archive_case.xml',
        'wizard/print_case.xml',
        'wizard/archive_selected_cases.xml',
        'data/case_email_template.xml',
        'data/appointment_email_template.xml',
        'data/payment_acceptance_email.xml',
        'data/patient_email_template.xml',
        'data/doctor_email_template.xml',
        'data/nurse_email_template.xml',
        'data/appointment_reminder_email.xml',
        'data/sequence.xml',
        'data/cronjob.xml',
        'data/demo.xml',
        'views/menu.xml',
        'views/city.xml',
        'views/patient.xml',
        'views/doctor.xml',
        'views/speciality.xml',
        'views/case.xml',
        'views/appointment.xml',
        'views/staff.xml',
        'views/nurse.xml',
        'views/settings.xml',
        'views/qualifications.xml',
        'views/template.xml',
        'views/website_form.xml',
        'views/res_users_inherit.xml',
        'report/patient_detail.xml',
        'report/doctor_detail.xml',
        'report/nurse_detail.xml',
        'report/staff_detail.xml',
        'report/reports.xml',
        'report/case_detail.xml',
        'report/case_wizard_details.xml',
        'report/product_extentend.xml',
        'report/payment_bill.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
    'assets':{
        'web.assets_backend':[
            'as_hospital/static/src/xml/list_controller.xml',
            'as_hospital/static/src/js/list_controller.js',
        ],
    },
}
